// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ClinicalArticleCard.tsx": () => import("../components/mockups/ClinicalArticleCard.tsx"),
  "./components/mockups/ClinicalPearlsCardStack.tsx": () => import("../components/mockups/ClinicalPearlsCardStack.tsx"),
  "./components/mockups/MedicalComponentsDemo.tsx": () => import("../components/mockups/MedicalComponentsDemo.tsx"),
  "./components/mockups/MnemonicCard.tsx": () => import("../components/mockups/MnemonicCard.tsx"),
  "./components/mockups/OsceStationQuestion.tsx": () => import("../components/mockups/OsceStationQuestion.tsx"),
  "./components/mockups/RevisionSheetTable.tsx": () => import("../components/mockups/RevisionSheetTable.tsx")
};
